# Generated by Django 5.0.4 on 2024-04-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
